pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from the GitHub repository
                git 'https://github.com/sekhar334/HRMS-Frontend-main.git'
            }
        }
        
        stage('Install dependencies') {
            steps {
                // Install Node.js and Angular CLI dependencies
                sh 'npm install'
            }
        }
        
        stage('Build') {
            steps {
                // Build the Angular.js project
                sh 'npm run build'
            }
        }
        
        stage('Unit Tests') {
            steps {
                // Run unit tests for Angular.js project
                sh 'npm run test'
            }
        }
        
        stage('Deploy') {
            steps {
                // Deployment steps (e.g., copying build artifacts to a server)
                // Replace this with your deployment process
                sh 'echo "hrms"'
                // Add your deployment commands here
            }
        }
    }
    
    post {
        always {
            // Cleanup steps or notifications can go here
            // For example, you might want to clean up temporary files or send notifications
        }
    }
}

