pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from the GitHub repository
                git 'https://github.com/sekhar334/HRMS-Frontend-main.git '
            }
        }
        
        stage('Install Dependencies') {
            steps {
                // Install Node.js and npm (if not already installed)
                sh 'npm install'
            }
        }
        
        stage('Build') {
            steps {
                // Build the Angular.js project
                sh 'npm run build'  // You might need to adjust the command based on your project configuration
            }
        }
        
        stage('Deploy') {
            steps {
                // Deploy the built files to your server or any required destination
                // This step can be adjusted based on your deployment needs (e.g., copying files to a server)
                sh 'echo "Deploying your Angular.js project"'
                // Add deployment steps here
            }
        }
    }
    
    post {
        always {
            // Clean up or perform any post-build actions if necessary
            // For example, notifications, archiving artifacts, etc.
        }
    }
}
