pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                // Checkout code from the GitHub repository
                git 'https://github.com/sekhar334/HRMS-Frontend-main.git'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                // Install Node.js and npm
                sh 'sudo apt-get install -y nodejs'
                
                // Install Angular CLI globally
                sh 'sudo npm install -g @angular/cli'
                
                // Install project dependencies
                sh 'npm install'
            }
        }
        
        stage('Run Tests') {
            steps {
                // Run tests using Angular CLI
                sh 'ng test'
            }
        }
        
        stage('Build') {
            steps {
                // Build the Angular project
                sh 'ng build --prod'
                
                // You can deploy or archive the built artifacts as needed
                // For example, archive the build artifacts
                archiveArtifacts artifacts: 'dist/*'
            }
        }
    }
    
    post {
        success {
            // This block will execute if the pipeline succeeds
            echo 'Angular.js build and test pipeline succeeded!'
        }
        
        failure {
            // This block will execute if the pipeline fails
            echo 'Angular.js build and test pipeline failed!'
        }
    }
}


